openapi: 3.0.1
info:
  title: Users CRUD operation
  description: This is the demo assignment for user crud operations
  contact:
    email: sneha.lanjewar@accionlabs.com
  version: 1.0.0
servers:
- url : http://localhost:5000/api/
tags:
- name: users
  description: A sample user related api
paths:
  /user:
    post:
      tags:
      - users
      summary: Create a new user
      description: Create a new user
      operationId: create
      consumes:
        - "application/json"
      produces:
      - "application/json"
      requestBody:
        description: Required fields to create *User*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        "200":
          description: "User created"
        "400":
          description: "Invalid Request"
    get:
      tags:
      - users
      summary: Fetches all users
      description: Fetches all users
      operationId: list
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        400:
          description: Incorrect Request Parameters
        500:
          description: Internal Server Error
components:
  schemas:
    user:
      type: "object"
      properties:
        firstName:
          type: "string"        
        lastName:
          type: "string"        
        email:
          type: "string"
        mobileNumber:
          type: "string"
     